use Weather_v2;
go

select a.name, 
       a.last_updated_epoch,
       a.last_updated,
       a.temp_c,
       a.temp_f,
       a.isday,
       a.current_conditions,
       a.wind_mph,
       a.wind_kph,
       a.wind_degree,
       a.wind_dir,
       a.pressure_mb,
       a.pressure_in,
       a.precip_mm,
       a.precip_in,
       a.humidity,
       a.cloud,
       a.feelslike_c,
       a.feelslike_f,
       a.windchill_c,
       a.windchill_f,
       a.heatindex_c,
       a.heatindex_f,
       a.dewpoint_c,
       a.dewpoint_f,
       a.vis_km,
       a.vis_miles,
       a.uv,
       a.gust_mph,
       a.gust_kph

from dbo.WeatherJsonLoad lvl1
cross apply openjson(lvl1.JsonData) with (
    name varchar(50) '$.location.name', 
    last_updated_epoch int '$.current.last_updated_epoch',
    last_updated datetime '$.current.last_updated',
    temp_c float '$.current.temp_c',
    temp_f float '$.current.temp_f',
    isday bit '$.current.is_day',
    current_conditions varchar(255) '$.current.condition.text',
    wind_mph float '$.current.wind_mph',
    wind_kph float '$.current.wind_kph',
    wind_degree float '$.current.wind_degree',
    wind_dir varchar(25) '$.current.wind_dir',
    pressure_mb float '$.current.pressure_mb',
    pressure_in float '$.current.pressure_in',
    precip_mm float '$.current.precip_mm',
    precip_in float '$.current.precip_in',
    humidity float '$.current.humidity',
    cloud float '$.current.cloud',
    feelslike_c float '$.current.feelslike_c',
    feelslike_f float '$.current.feelslike_f',
    windchill_c float '$.current.windchill_c',
    windchill_f float '$.current.windchill_f',
    heatindex_c float '$.current.heatindex_c',
    heatindex_f float '$.current.heatindex_f',
    dewpoint_c float '$.current.dewpoint_c',
    dewpoint_f float '$.current.dewpoint_f',
    vis_km float '$.current.vis_km',
    vis_miles float '$.current.vis_miles',
    uv float '$.current.uv',
    gust_mph float '$.current.gust_mph',
    gust_kph float '$.current.gust_kph'
) as a