USE Weather_v2;
GO

    SELECT l.LocationID,
        a.name,
        a.last_updated_epoch,
        a.last_updated,
        a.temp_c,
        a.temp_f,
        a.isday,
        a.current_conditions,
        a.wind_mph,
        a.wind_kph,
        a.wind_degree,
        a.wind_dir,
        a.pressure_mb,
        a.pressure_in,
        a.precip_mm,
        a.precip_in,
        a.humidity,
        a.cloud,
        a.feelslike_c,
        a.feelslike_f,
        a.windchill_c,
        a.windchill_f,
        a.heatindex_c,
        a.heatindex_f,
        a.dewpoint_c,
        a.dewpoint_f,
        a.vis_km,
        a.vis_miles,
        a.uv,
        a.gust_mph,
        a.gust_kph
    FROM dbo.WeatherJsonLoad lvl1
    CROSS APPLY openjson(lvl1.JsonData) WITH (
            name VARCHAR(50) '$.location.name',
            last_updated_epoch INT '$.current.last_updated_epoch',
            last_updated DATETIME '$.current.last_updated',
            temp_c NUMERIC(6, 2) '$.current.temp_c',
            temp_f NUMERIC(6, 2) '$.current.temp_f',
            isday BIT '$.current.is_day',
            current_conditions VARCHAR(50) '$.current.condition.text',
            wind_mph NUMERIC(6, 2) '$.current.wind_mph',
            wind_kph NUMERIC(6, 2) '$.current.wind_kph',
            wind_degree NUMERIC(6, 2) '$.current.wind_degree',
            wind_dir VARCHAR(25) '$.current.wind_dir',
            pressure_mb NUMERIC(6, 2) '$.current.pressure_mb',
            pressure_in NUMERIC(6, 2) '$.current.pressure_in',
            precip_mm NUMERIC(6, 2) '$.current.precip_mm',
            precip_in NUMERIC(6, 2) '$.current.precip_in',
            humidity NUMERIC(6, 2) '$.current.humidity',
            cloud NUMERIC(6, 2) '$.current.cloud',
            feelslike_c NUMERIC(6, 2) '$.current.feelslike_c',
            feelslike_f NUMERIC(6, 2) '$.current.feelslike_f',
            windchill_c NUMERIC(6, 2) '$.current.windchill_c',
            windchill_f NUMERIC(6, 2) '$.current.windchill_f',
            heatindex_c NUMERIC(6, 2) '$.current.heatindex_c',
            heatindex_f NUMERIC(6, 2) '$.current.heatindex_f',
            dewpoint_c NUMERIC(6, 2) '$.current.dewpoint_c',
            dewpoint_f NUMERIC(6, 2) '$.current.dewpoint_f',
            vis_km NUMERIC(6, 2) '$.current.vis_km',
            vis_miles NUMERIC(6, 2) '$.current.vis_miles',
            uv NUMERIC(6, 2) '$.current.uv',
            gust_mph NUMERIC(6, 2) '$.current.gust_mph',
            gust_kph NUMERIC(6, 2) '$.current.gust_kph'
            ) AS a
    INNER JOIN dbo.Location l
        ON l.name = a.name
