select l.locationid,
       jsondata -> 'current' ->> 'last_updated_epoch' as last_updated_epoch,
       jsondata -> 'current' ->> 'last_updated' as last_updated,
       jsondata -> 'current' ->> 'temp_c' as temp_c,
       jsondata -> 'current' ->> 'temp_f' as temp_f,
       jsondata -> 'current' ->> 'is_day' as is_day,
       jsondata -> 'current' -> 'condition' ->> 'text' as current_condition,
       jsondata -> 'current' ->> 'wind_mph' as wind_mph,
       jsondata -> 'current' ->> 'wind_kph' as wind_kph,
       jsondata -> 'current' ->> 'wind_degree' as wind_degree,
       jsondata -> 'current' ->> 'wind_dir' as wind_dir,
       jsondata -> 'current' ->> 'pressure_mb' as pressure_mb,
       jsondata -> 'current' ->> 'pressure_in' as pressure_in,
       jsondata -> 'current' ->> 'precip_mm' as precip_mm,
       jsondata -> 'current' ->> 'precip_in' as precip_in,
       jsondata -> 'current' ->> 'humidity' as humidity,
       jsondata -> 'current' ->> 'cloud' as cloud,
       jsondata -> 'current' ->> 'feelslike_c' as feelslike_c,
       jsondata -> 'current' ->> 'feelslike_f' as feelslike_f,
       jsondata -> 'current' ->> 'windchill_c' as windchill_c,
       jsondata -> 'current' ->> 'windchill_f' as windchill_f,
       jsondata -> 'current' ->> 'heatindex_c' as heatindex_c,
       jsondata -> 'current' ->> 'heatindex_f' as heatindex_f,
       jsondata -> 'current' ->> 'dewpoint_c' as dewpoint_c,
       jsondata -> 'current' ->> 'dewpoint_f' as dewpoint_f,
       jsondata -> 'current' ->> 'vis_km' as vis_km,
       jsondata -> 'current' ->> 'vis_miles' as vis_miles,
       jsondata -> 'current' ->> 'uv' as uv,
       jsondata -> 'current' ->> 'gust_mph' as gust_mph,
       jsondata -> 'current' ->> 'gust_kph' as gust_kph
into _current_conditions 
from weatherjsonload wjl
inner join public.location l on jsondata -> 'location' ->> 'name' = l."name"
where wjl.processed = 0;