SELECT l.locationid,
       arr.item_object ->> 'date' as date,
       arr.item_object ->> 'date_epoch' as date_epoch,
       arr2.hour_object ->> 'time_epoch' as time_epoch,
       arr2.hour_object ->> 'time' as time,
       arr2.hour_object ->> 'temp_c' as temp_c,
       arr2.hour_object ->> 'temp_f' as temp_f,
       cast(arr2.hour_object ->> 'is_day' as int4) as is_day,
       arr2.hour_object -> 'condition' ->> 'text' as HourlyConditions,
       arr2.hour_object -> 'condition' ->> 'icon' as HourlyConditionsIconURL,
       arr2.hour_object -> 'condition' ->> 'code' as HourlyConditionsCode,
       arr2.hour_object ->> 'wind_mph' as wind_mph,
       arr2.hour_object ->> 'wind_kph' as wind_kph,
       arr2.hour_object ->> 'wind_degree' as wind_degree,
       arr2.hour_object ->> 'wind_dir' as wind_direction,
       arr2.hour_object ->> 'pressure_mb' as pressure_mb,
       arr2.hour_object ->> 'pressure_in' as pressure_in,
       arr2.hour_object ->> 'precip_mm' as precip_mm,
       arr2.hour_object ->> 'precip_in' as precip_in,
       arr2.hour_object ->> 'snow_cm' as snow_cm,
       arr2.hour_object ->> 'humidity' as humidity,
       arr2.hour_object ->> 'cloud' as cloud,
       arr2.hour_object ->> 'feelslike_c' as feelslike_c,
       arr2.hour_object ->> 'feelslike_f' as feelslike_f,
       arr2.hour_object ->> 'windchill_c' as windchill_c,
       arr2.hour_object ->> 'windchill_f' as windchill_f,
       arr2.hour_object ->> 'heatindex_c' as heatindex_c,
       arr2.hour_object ->> 'heatindex_f' as heatindex_f,
       arr2.hour_object ->> 'dewpoint_c' as dewpoint_c,
       arr2.hour_object ->> 'dewpoint_f' as dewpoint_f,
       cast(arr2.hour_object ->> 'will_it_rain' as int4) as will_it_rain,
       arr2.hour_object ->> 'chance_of_rain' as chance_of_rain,
       cast(arr2.hour_object ->> 'will_it_snow' as int) as will_it_snow,
       arr2.hour_object ->> 'chance_of_snow' as chance_of_snow,
       arr2.hour_object ->> 'vis_km' as vis_km,
       arr2.hour_object ->> 'vis_miles' as vis_miles,
       arr2.hour_object ->> 'gust_mph' as gust_mph,
       arr2.hour_object ->> 'gust_kph' as gust_kph,
       arr2.hour_object ->> 'uv' as uv,
       arr2.position 
FROM public.weatherjsonload wjl
CROSS JOIN jsonb_array_elements(jsondata ->'forecast'->'forecastday') with ordinality arr(item_object, position)
CROSS JOIN jsonb_array_elements(arr.item_object -> 'hour') with ordinality arr2(hour_object, position)
INNER JOIN public.location l ON wjl.jsondata -> 'location' ->> 'name' = l."name";