-- Role: postgres
-- DROP ROLE IF EXISTS postgres;

CREATE ROLE python WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:5jAeVsLk2AWanxaK41Dh5w==$gk7a8Gcw1gs5LbXSMz3RdOn8G8aE3LTe7pfPV3R04yo=:p15u1tRLHR+SQDgddVIMPpE5hs5bSFZfXivtulhR4N4=';
  commit 