USE Weather_v2;

DROP PROCEDURE IF EXISTS insert_hourly_forecast;

DELIMITER //

CREATE PROCEDURE insert_hourly_forecast ()
BEGIN
    
    DROP TABLE IF EXISTS hourly_source;
    
    CREATE TEMPORARY TABLE hourly_source AS (
    SELECT id,  
           jsondata ->> '$.location.name' AS location_name,
           forecast_hour, 
           forecast_time_epoch,
           temp_c,
           temp_f,
           is_day,
           hourlycondition,
           wind_mph,
           wind_kph,
           wind_degree,
           wind_dir,
           pressure_mb,
           pressure_in,
           precip_mm,
           precip_in, 
           snow_cm,
           humidity,
           cloud,
           feelslike_c,
           feelslike_f,
           windchill_c,
           windchill_f,
           heatindex_c,
           heatindex_f,
           dewpoint_c,
           dewpoint_f,
           will_it_rain,
           chance_of_rain,
           will_it_snow,
           chance_of_snow,
           vis_km,
           vis_miles,
           gust_mph, 
           gust_kph, 
           uv
    FROM Weather_v2.weatherjsonload wjl,
    JSON_TABLE(jsondata, '$.forecast.forecastday[*]' columns (
        
        NESTED PATH '$.hour[*]' columns (
            id for ordinality,
            forecast_hour DATETIME PATH '$.time', 
            forecast_time_epoch INT PATH '$.time_epoch',
            temp_c NUMERIC(9,2) PATH '$.temp_c',
            temp_f NUMERIC(9,2) PATH '$.temp_f',
            is_day BIT PATH '$.is_day',
            hourlycondition VARCHAR(50) PATH '$.condition.text',
            wind_mph NUMERIC(9,2) PATH '$.wind_mph',
            wind_kph NUMERIC(9,2) PATH '$.wind_kph',
            wind_degree NUMERIC(9,2) PATH '$.wind_degree',
            wind_dir varchar(50) PATH '$.wind_dir',
            pressure_mb NUMERIC(9,2) PATH '$.pressure_mb',
            pressure_in NUMERIC(9,2) PATH '$.pressure_in',
            precip_mm NUMERIC(9,2) PATH '$.precip_mm', 
            precip_in NUMERIC(9,2) PATH '$.precip_in', 
            snow_cm NUMERIC(9,2) PATH '$.snow_cm',
            humidity NUMERIC(9,2) PATH '$.humidity', 
            cloud INT PATH '$.cloud',
            feelslike_c NUMERIC(9,2) PATH '$.feelslike_c',
            feelslike_f NUMERIC(9,2) PATH '$.feelslike_f',
            windchill_c NUMERIC(9,2) PATH '$.windchill_c',
            windchill_f NUMERIC(9,2) PATH '$.windchill_f',
            heatindex_c NUMERIC(9,2) PATH '$.heatindex_c',
            heatindex_f NUMERIC(9,2) PATH '$.heatindex_f',
            dewpoint_c NUMERIC(9,2) PATH '$.dewpoint_c',
            dewpoint_f NUMERIC(9,2) PATH '$.dewpoint_f',
            will_it_rain NUMERIC(9,2) PATH '$.will_it_rain',
            chance_of_rain NUMERIC(9,2) PATH '$.chance_of_rain',
            will_it_snow NUMERIC(9,2) PATH '$.will_it_snow',
            chance_of_snow NUMERIC(9,2) PATH '$.chance_of_snow',
            vis_km NUMERIC(9,2) PATH '$.vis_km',
            vis_miles NUMERIC(9,2) PATH '$.vis_miles',
            gust_mph NUMERIC(9,2) PATH '$.gust_mph',
            gust_kph NUMERIC(9,2) PATH '$.gust_kph', 
            uv NUMERIC(9,2) PATH '$.uv'
            )
        
        )
    ) hourly
    WHERE processed = 0
    );
    
    INSERT INTO Weather_v2.HourlyForecast(LocationID, forecast_hour, forecast_time_epoch, temp_c, temp_f, is_day, hourlycondition, wind_mph,
                                          wind_kph, wind_degree, wind_dir, pressure_mb, pressure_in, precip_mm, precip_in, snow_cm, humidity, cloud,
                                          feelslike_c, feelslike_f, windchill_c, windchill_f, heatindex_c, heatindex_f, dewpoint_c, dewpoint_f,
                                          will_it_rain, chance_of_rain, will_it_snow, chance_of_snow, vis_km, vis_miles, gust_mph, gust_kph, uv)
    SELECT LocationID, 
		forecast_hour, 
        forecast_time_epoch, 
        temp_c, 
        temp_f, 
        is_day, 
        hourlycondition, 
        wind_mph,
        wind_kph, 
        wind_degree, 
        wind_dir, 
        pressure_mb, 
        pressure_in, 
        precip_mm, 
        precip_in, 
        snow_cm, 
        humidity, 
        cloud,
        feelslike_c, 
        feelslike_f, 
        windchill_c, 
        windchill_f, 
        heatindex_c, 
        heatindex_f, 
        dewpoint_c, 
        dewpoint_f,
        will_it_rain, 
        chance_of_rain, 
        will_it_snow, 
        chance_of_snow, 
        vis_km, 
        vis_miles, 
        gust_mph, 
        gust_kph, 
        uv
	ON DUPLICATE KEY UPDATE temp_c = temp_c,
                            temp_f = temp_f,
                            is_day = is_day,
                            hourlycondition = hourlycondition,
                            wind_mph = wind_mph,
                            wind_kph = wind_kph,
                            wind_degree = wind_degree,
                            wind_dir = wind_dir,
                            pressure_mb = pressure_mb,
                            pressure_in = pressure_in,
                            precip_mm = precip_mm,
                            precip_in = precip_in, 
                            snow_cm = snow_cm, 
                            humidity = humidity,
                            cloud = cloud,
                            feelslike_c = feelslike_c,
                            feelslike_f = feelslike_f,
                            windchill_c = windchill_c,
                            windchill_f = windchill_f,
                            heatindex_c = heatindex_c,
                            heatindex_f = heatindex_f,
                            dewpoint_c = dewpoint_c,
                            dewpoint_f = dewpoint_f,
                            will_it_rain = will_it_rain,
                            chance_of_rain = chance_of_rain,
                            will_it_snow = will_it_snow,
                            vis_km = vis_km,
                            vis_miles = vis_miles,
                            gust_mph = gust_mph,
                            gust_kph = gust_kph,
                            uv = uv ;
    
END;
//

DELIMITER ;
