use Weather_v2;

DROP PROCEDURE IF EXISTS insert_current_conditions;

delimiter //

CREATE PROCEDURE insert_current_conditions ()
BEGIN
    DROP TABLE IF EXISTS source;
    
    CREATE TEMPORARY TABLE source AS (
    SELECT jsondata ->> '$.location.name' AS location_name,
           last_updated_epoch,
           last_updated,
           temp_c,
           temp_f,
           isday,
           current_conditions,
           wind_mph,
           wind_kph,
           wind_degree,
           wind_direction,
           pressure_mb,
           pressure_in,
           precip_mm, 
           precip_in, 
           humidity,
           cloud,
           feelslike_c,
           feelslike_f,
           windchill_c,
           windchill_f,
           heatindex_c,
           heatindex_f,
           dewpoint_c,
           dewpoint_f,
           vis_km,
           vis_miles,
           uv,
           gust_mph,
           gust_kph
    from weatherjsonload a,
    JSON_TABLE(jsondata, '$.current' COLUMNS (
        last_updated_epoch INT PATH '$.last_updated_epoch',
        last_updated DATETIME PATH '$.last_updated',
        temp_c NUMERiC(6,2) PATH '$.temp_c',
        temp_f NUMERIC(6,2) PATH '$.temp_f',
        isday BIT PATH '$.is_day',
        current_conditions VARCHAR(50) PATH '$.condition.text',
        wind_mph NUMERIC(6,2) PATH '$.wind_mph',
        wind_kph NUMERIC(6,2) PATH '$.wind_kph',
        wind_degree NUMERIC(6,2) PATH '$.wind_degree',
        wind_direction VARCHAR(50) PATH '$.wind_dir',
        pressure_mb NUMERIC(6,2) PATH '$.pressure_mb',
        pressure_in NUMERIC(6,2) PATH '$.pressure_in',
        precip_mm NUMERIC(6,2) PATH '$.precip_mm',
        precip_in numeric(6,2) PATH '$.precip_in',
        humidity NUMERIC(6,2) PATH '$.humidity',
        cloud INT PATH '$.cloud',
        feelslike_c NUMERIC(6,2) PATH '$.feelslike_c',
        feelslike_f NUMERIC(6,2) PATH '$.feelslike_f',
        windchill_c NUMERIC(6,2) PATH '$.windchill_c',
        windchill_f NUMERIC(6,2) PATH '$.windchill_f',
        heatindex_c NUMERIC(6,2) PATH '$.heatindex_c',
        heatindex_f NUMERIC(6,2) PATH '$.heatindex_f',
        dewpoint_c NUMERIC(6,2) PATH '$.dewpoint_c',
        dewpoint_f NUMERIC(6,2) PATH '$.dewpoint_f',
        vis_km NUMERIC(6,2) PATH '$.vis_km',
        vis_miles NUMERIC(6,2) PATH '$.vis_miles',
        uv NUMERIC(6,2) PATH '$.uv',
        gust_mph NUMERIC(6,2) PATH '$.gust_mph',
        gust_kph NUMERIC(6,2) PATH '$.gust_kph'

    )) AS current
    WHERE processed = 0 );
    
    INSERT Weather_v2.CurrentConditions(LocationID, last_updated_epoch, last_updated, temp_c, temp_f, isday, current_conditions, wind_mph,
                                        wind_kph, wind_degree, wind_direction, pressure_mb, pressure_in, precip_mm, precip_in, humidity,
                                        cloud, feelslike_c, feelslike_f, windchill_c, windchill_f, heatindex_c, heatindex_f, dewpoint_c,
                                        dewpoint_f, vis_km, vis_miles, uv, gust_mph, gust_kph)
	SELECT LocationID,
           last_updated_epoch,
		   last_updated,
		   temp_c,
		   temp_f,
		   isday,
		   current_conditions,
		   wind_mph,
		   wind_kph,
		   wind_degree,
		   wind_direction,
		   pressure_mb,
		   pressure_in,
		   precip_mm,
		   precip_in,
		   humidity,
		   cloud,
		   feelslike_c,
		   feelslike_f,
		   windchill_c,
		   windchill_f,
		   heatindex_c,
		   heatindex_f, 
		   dewpoint_c,
		   dewpoint_f,
		   vis_km,
		   vis_miles,
		   uv,
		   gust_mph, 
		   gust_kph
    FROM source AS a
    INNER JOIN Weather_v2.Location b ON a.location_name = b.name 
    ON DUPLICATE KEY UPDATE last_updated_epoch = a.last_updated_epoch,
                            last_updated = a.last_updated,
                            temp_c = a.temp_c,
                            temp_f = a.temp_f,
                            isday = a.isday,
                            current_conditions = a.current_conditions,
                            wind_mph = a.wind_mph,
                            wind_kph = a.wind_kph,
                            wind_degree = a.wind_degree,
                            wind_direction = a.wind_direction,
                            pressure_mb = a.pressure_mb,
                            pressure_in = a.pressure_in,
                            precip_mm = a.precip_mm,
                            precip_in = a.precip_in,
                            humidity = a.humidity,
                            cloud = a.cloud,
                            feelslike_c = a.feelslike_c,
                            feelslike_f = a.feelslike_f,
                            windchill_c = a.windchill_c,
                            windchill_f = a.windchill_f,
                            heatindex_c = a.heatindex_c,
                            dewpoint_c = a.dewpoint_c,
                            dewpoint_f = a.dewpoint_f,
                            vis_km = a.vis_km,
                            vis_miles = a.vis_miles,
                            uv = a.uv,
                            gust_mph = a.gust_mph,
                            gust_kph = a.gust_kph ;

END;
//

delimiter ;
