DROP TABLE CurrentConditions;

CREATE TABLE CurrentConditions(
    CurrentConditionID bigint GENERATED ALWAYS AS IDENTITY,
    locationid bigint NULL, 
    last_updated_epoch int8 NULL,
    last_updated timestamp NULL,
    temp_c float NULL,
    temp_f float NULL,
    isday bit NULL,
    current_conditions varchar(255) NULL,
    wind_mph float NULL,
    wind_kph float NULL,
    wind_degree float NULL,
    wind_direction varchar(255) NULL,
    pressure_mb float NULL,
    pressure_in float NULL,
    precip_mm float NULL,
    precip_in float NULL,
    humidity float NULL,
    cloud float NULL,
    feelslike_c float NULL,
    feelslike_f float NULL,
    windchill_c float NULL,
    windchill_f float NULL,
    heatindex_c float NULL,
    heatindex_f float NULL,
    dewpoint_c float NULL,
    dewpoint_f float NULL,
    vis_km float NULL,
    vis_miles float NULL,
    uv float NULL,
    gust_mph float NULL,
    gust_kph float NULL,
 PRIMARY KEY (CurrentConditionID) 

) ;