use Weather_v2;

SELECT jsondata ->> '$.location.name',
       last_updated_epoch,
       last_updated,
       temp_c,
       temp_f,
       isday,
       current_conditions,
       wind_mph,
       wind_kph,
       wind_degree,
       wind_direction,
       pressure_mb,
       pressure_in,
       precip_mm, 
       precip_in, 
       humidity,
       cloud,
       feelslike_c,
       feelslike_f,
       windchill_c,
       windchill_f,
       heatindex_c,
       heatindex_f,
       dewpoint_c,
       dewpoint_f,
       vis_km,
       vis_miles,
       uv,
       gust_mph,
       gust_kph
from weatherjsonload a,
JSON_TABLE(jsondata, '$.current' COLUMNS (
    last_updated_epoch INT PATH '$.last_updated_epoch',
    last_updated DATETIME PATH '$.last_updated',
    temp_c NUMERiC(6,2) PATH '$.temp_c',
    temp_f NUMERIC(6,2) PATH '$.temp_f',
    isday BIT PATH '$.is_day',
    current_conditions VARCHAR(50) PATH '$.condition.text',
    wind_mph NUMERIC(6,2) PATH '$.wind_mph',
    wind_kph NUMERIC(6,2) PATH '$.wind_kph',
    wind_degree NUMERIC(6,2) PATH '$.wind_degree',
    wind_direction VARCHAR(50) PATH '$.wind_dir',
    pressure_mb NUMERIC(6,2) PATH '$.pressure_mb',
    pressure_in NUMERIC(6,2) PATH '$.pressure_in',
    precip_mm NUMERIC(6,2) PATH '$.precip_mm',
    precip_in numeric(6,2) PATH '$.precip_in',
    humidity NUMERIC(6,2) PATH '$.humidity',
    cloud INT PATH '$.cloud',
    feelslike_c NUMERIC(6,2) PATH '$.feelslike_c',
    feelslike_f NUMERIC(6,2) PATH '$.feelslike_f',
    windchill_c NUMERIC(6,2) PATH '$.windchill_c',
    windchill_f NUMERIC(6,2) PATH '$.windchill_f',
    heatindex_c NUMERIC(6,2) PATH '$.heatindex_c',
    heatindex_f NUMERIC(6,2) PATH '$.heatindex_f',
    dewpoint_c NUMERIC(6,2) PATH '$.dewpoint_c',
    dewpoint_f NUMERIC(6,2) PATH '$.dewpoint_f',
    vis_km NUMERIC(6,2) PATH '$.vis_km',
    vis_miles NUMERIC(6,2) PATH '$.vis_miles',
    uv NUMERIC(6,2) PATH '$.uv',
    gust_mph NUMERIC(6,2) PATH '$.gust_mph',
    gust_kph NUMERIC(6,2) PATH '$.gust_kph'

)) AS current
WHERE processed = 0; 

