use Weather_v2;

    SELECT hourly.id,  
           a.jsondata ->> '$.location.name' AS locationName,
           hourly.hourlyTime, 
           hourly.hourlyTimeEpoch,
           hourly.hourlyTempC,
           hourly.hourlyTempF,
           hourly.hourlyIsDay,
           hourly.hourlyConditions,
           hourly.hourlyWindMPH,
           hourly.hourlyWindKPH,
           hourly.hourlyWindDegree,
           hourly.hourlyWindDirection,
           hourly.hourlyPressureMB,
           hourly.hourlyPressureIN,
           hourly.hourlySnowCM,
           hourly.hourlyHumidity,
           hourly.hourlyCloud,
           hourly.hourlyFeelsLikeC,
           hourly.hourlyFeelsLikeF,
           hourly.hourlyWindChillC,
           hourly.hourlyWindChillF,
           hourly.hourlyHeatIndexC,
           hourly.hourlyHeatIndexF,
           hourly.hourlyDewPointC,
           hourly.hourlyDewPointF,
           hourly.hourlyWillItRain,
           hourly.hourlyChanceOfRain,
           hourly.hourlyWillItSnow,
           hourly.hourlyChanceOfSnow,
           hourly.hourlyVisKM,
           hourly.hourlyVisMiles,
           hourly.hourlyGustMPH, 
           hourly.hourlyGustKPH, 
           hourly.hourlyUV
    FROM Weather_v2.weatherjsonload AS a,
    JSON_TABLE(jsondata, '$.forecast.forecastday[*]' columns (
        
        nested PATH '$.hour[*]' columns (
            id for ordinality,
            
            hourlyTime DATETIME PATH '$.time', 
            hourlyTimeEpoch INT PATH '$.time_epoch',
            hourlyTempC NUMERIC(9,2) PATH '$.temp_c',
            hourlyTempF NUMERIC(9,2) PATH '$.temp_f',
            hourlyIsDay BIT PATH '$.is_day',
            hourlyConditions VARCHAR(50) PATH '$.condition.text',
            hourlyWindMPH NUMERIC(9,2) PATH '$.wind_mph',
            hourlyWindKPH NUMERIC(9,2) PATH '$.wind_kph',
            hourlyWindDegree NUMERIC(9,2) PATH '$.wind_degree',
            hourlyWindDirection varchar(50) PATH '$.wind_dir',
            hourlyPressureMB NUMERIC(9,2) PATH '$.pressure_mb',
            hourlyPressureIN NUMERIC(9,2) PATH '$.pressure_in',
            hourlySnowCM NUMERIC(9,2) PATH '$.snow_cm',
            hourlyHumidity NUMERIC(9,2) PATH '$.humidity', 
            hourlyCloud INT PATH '$.cloud',
            hourlyFeelsLikeC NUMERIC(9,2) PATH '$.feelslike_c',
            hourlyFeelsLikeF NUMERIC(9,2) PATH '$.feelslike_f',
            hourlyWindChillC NUMERIC(9,2) PATH '$.windchill_c',
            hourlyWindChillF NUMERIC(9,2) PATH '$.windchill_f',
            hourlyHeatIndexC NUMERIC(9,2) PATH '$.heatindex_c',
            hourlyHeatIndexF NUMERIC(9,2) PATH '$.heatindex_f',
            hourlyDewPointC NUMERIC(9,2) PATH '$.dewpoint_c',
            hourlyDewPointF NUMERIC(9,2) PATH '$.dewpoint_f',
            hourlyWillItRain NUMERIC(9,2) PATH '$.will_it_rain',
            hourlyChanceOfRain NUMERIC(9,2) PATH '$.chance_of_rain',
            hourlyWillItSnow NUMERIC(9,2) PATH '$.will_it_snow',
            hourlyChanceOfSnow NUMERIC(9,2) PATH '$.chance_of_snow',
            hourlyVisKM NUMERIC(9,2) PATH '$.vis_km',
            hourlyVisMiles NUMERIC(9,2) PATH '$.vis_miles',
            hourlyGustMPH NUMERIC(9,2) PATH '$.gust_mph',
            hourlyGustKPH NUMERIC(9,2) PATH '$.gust_kph', 
            hourlyUV NUMERIC(9,2) PATH '$.uv'
            )
        
        )
    ) hourly
    WHERE processed = 0;


