use Weather_v2;

-- forecastDateEpoch int path '$.date_epoch',

select hourly.id,  
       jsondata ->> '$.location.name' as locationName,
       hourly.hourlyTime, 
       hourly.hourlyTimeEpoch,
       hourlyTempC,
       hourlyTempF,
       hourlyIsDay,
       hourlyConditions,
       hourlyWindMPH,
       hourlyWindKPH,
       hourlyWindDegree,
       hourlyWindDirection,
       hourlyPressureMB,
       hourlyPressureIN,
       hourlySnowCM,
       hourlyHumidity,
       hourlyCloud,
       hourlyFeelsLikeC,
       hourlyFeelsLikeF,
       hourlyWindChillC,
       hourlyWindChillF,
       hourlyHeatIndexC,
       hourlyHeatIndexF,
       hourlyDewPointC,
       hourlyDewPointF,
       hourlyWillItRain,
       hourlyChanceOfRain,
       hourlyWillItSnow,
       hourlyChanceOfSnow,
       hourlyVisKM,
       hourlyVisMiles,
       hourlyGustMPH, 
       hourlyGustKPH, 
       hourlyUV
from Weather_v2.weatherjsonload wjl,
json_table(jsondata, '$.forecast.forecastday[*]' columns (
    
    nested path '$.hour[*]' columns (
        id for ordinality,
        hourlyTime datetime path '$.time', 
        hourlyTimeEpoch int path '$.time_epoch',
        hourlyTempC numeric(9,2) path '$.temp_c',
        hourlyTempF numeric(9,2) path '$.temp_f',
        hourlyIsDay bit path '$.is_day',
        hourlyConditions varchar(50) path '$.condition.text',
        hourlyWindMPH numeric(9,2) path '$.wind_mph',
        hourlyWindKPH numeric(9,2) path '$.wind_kph',
        hourlyWindDegree numeric(9,2) path '$.wind_degree',
        hourlyWindDirection varchar(50) path '$.wind_dir',
        hourlyPressureMB numeric(9,2) path '$.pressure_mb',
        hourlyPressureIN numeric(9,2) path '$.pressure_in',
        hourlySnowCM numeric(9,2) path '$.snow_cm',
        hourlyHumidity numeric(9,2) path '$.humidity', 
        hourlyCloud int path '$.cloud',
        hourlyFeelsLikeC numeric(9,2) path '$.feelslike_c',
        hourlyFeelsLikeF numeric(9,2) path '$.feelslike_f',
        hourlyWindChillC numeric(9,2) path '$.windchill_c',
        hourlyWindChillF numeric(9,2) path '$.windchill_f',
        hourlyHeatIndexC numeric(9,2) path '$.heatindex_c',
        hourlyHeatIndexF numeric(9,2) path '$.heatindex_f',
        hourlyDewPointC numeric(9,2) path '$.dewpoint_c',
        hourlyDewPointF numeric(9,2) path '$.dewpoint_f',
        hourlyWillItRain numeric(9,2) path '$.will_it_rain',
        hourlyChanceOfRain numeric(9,2) path '$.chance_of_rain',
        hourlyWillItSnow numeric(9,2) path '$.will_it_snow',
        hourlyChanceOfSnow numeric(9,2) path '$.chance_of_snow',
        hourlyVisKM numeric(9,2) path '$.vis_km',
        hourlyVisMiles numeric(9,2) path '$.vis_miles',
        hourlyGustMPH numeric(9,2) path '$.gust_mph',
        hourlyGustKPH numeric(9,2) path '$.gust_kph', 
        hourlyUV numeric(9,2) path '$.uv'
        )
    
    )
) hourly
order by jsondata ->> '$.location.name',
          hourlyTimeEpoch;